/*
Navicat SQL Server Data Transfer

Source Server         : sqlserver
Source Server Version : 105000
Source Host           : 127.0.0.1:1433
Source Database       : platformmanage
Source Schema         : dbo

Target Server Type    : SQL Server
Target Server Version : 105000
File Encoding         : 65001

Date: 2019-09-18 18:35:55
*/


-- ----------------------------
-- Table structure for t_user
-- ----------------------------
DROP TABLE [dbo].[t_user]
GO
CREATE TABLE [dbo].[t_user] (
[id] int NOT NULL IDENTITY(1,1) ,
[platformid] varchar(50) NULL ,
[password] varchar(50) NULL ,
[platformname] varchar(50) NULL ,
[platformpizhunnum] varchar(50) NULL ,
[platformtechnology] varchar(50) NULL ,
[platformjibie] varchar(50) NULL ,
[platformadress] varchar(50) NULL ,
[platformxingtai] varchar(50) NULL ,
[gongjiandujian] varchar(50) NULL ,
[jingjinji] varchar(50) NULL ,
[jingjihangye] varchar(100) NULL ,
[mainxueku] varchar(100) NULL ,
[danweiname] varchar(50) NULL ,
[danweidaima] varchar(50) NULL ,
[danweifaren] varchar(50) NULL ,
[danweiphone] varchar(50) NULL ,
[danweileixing] varchar(50) NULL ,
[gongjiandanwei] varchar(50) NULL ,
[yzname] varchar(50) NULL ,
[yzsex] varchar(50) NULL ,
[yzbirth] nchar(10) NULL ,
[yzzhicheng] varchar(50) NULL ,
[yzzhuanye] varchar(50) NULL ,
[yzxueli] varchar(50) NULL ,
[yzxuewei] varchar(50) NULL ,
[yzphonenum] varchar(50) NULL ,
[yzofficialnum] varchar(50) NULL ,
[yzemail] varchar(50) NULL ,
[platwebname] varchar(50) NULL ,
[webadress] varchar(50) NULL ,
[tongxunadress] varchar(50) NULL ,
[youbian] varchar(50) NULL ,
[platformdate] datetime NULL ,
[quanxian] varchar(5) NULL 
)


GO
DBCC CHECKIDENT(N'[dbo].[t_user]', RESEED, 212)
GO

-- ----------------------------
-- Records of t_user
-- ----------------------------
SET IDENTITY_INSERT [dbo].[t_user] ON
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'1', N'1', N'1', N'圣诞节佛', N'1', N'工程技术研究中心', N'省级', N'北京市北京辖区东城区', N'', N'多单位联合共建', N'是', N'A农、林、牧、渔业01农业0111稻谷种植', N'110数学110.14数理逻辑和数学基础110.1410演绎逻辑学', N'', N'', N'', N'', N'', N'第1个', N'', N'', N'          ', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'2018-06-01 00:00:00.000', N'1')
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'3', N'2', N'0', N'2', N'2', N'工程技术研究中心', N'shengji', N'上海市上海辖区黄浦区', N'', N'', N'', N'A农、林、牧、渔业01农业0111稻谷种植', N'110数学110.14数理逻辑和数学基础110.1410演绎逻辑学', N'2', N'2', N'', N'', N'qita2', N'第1个', N'', N'', N'          ', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'2018-06-01 00:00:00.000', N'0')
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'4', N'3', N'0', N'3', N'3', N'重点实验室', N'省级', N'北京市北京辖县密云县', null, N'独建', N'是', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-01 00:00:00.000', N'0')
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'5', N'4', N'0', N'4', N'4', N'产业技术研究院', N'国家级', N'河南省郑州市中原区', null, N'多单位联合共建', N'是', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-01 00:00:00.000', N'0')
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'6', N'5', N'0', N'5', N'5', N'工程技术研究中心', N'省级', N'河南省郑州市二七区', null, N'独建', N'否', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-01 00:00:00.000', N'0')
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'7', N'6', N'0', N'6', N'6', N'重点实验室', N'国家级', N'河南省新乡市牧野区', null, N'多单位联合共建', N'否', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-01 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'8', N'7', N'0', N'7', N'7', N'产业技术研究院', N'省级', N'河南省新乡市凤泉区', null, N'独建', N'否', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-02 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'9', N'8', N'0', N'8', N'8', N'工程技术研究中心', N'国家级', null, null, N'多单位联合共建', N'否', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-02 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'10', N'9', N'0', N'9', N'9', N'重点实验室', N'省级', null, null, N'独建', N'否', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-02 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'11', N'10', N'0', N'10', N'10', N'产业技术研究院', N'国家级', null, null, N'多单位联合共建', N'否', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-02 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'12', N'11', N'0', N'11', N'11', N'工程技术研究中心', N'省级', null, null, N'独建', N'是', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-02 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'13', N'12', N'0', N'12', N'12', N'重点实验室', N'国家级', null, null, N'多单位联合共建', N'是', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-02 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'14', N'13', N'13', N'13', N'13', N'工程技术研究中心', N'省级', null, null, N'独建', N'是', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-02 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'15', N'14', N'14', N'14', N'14', N'工程技术研究中心', N'国家级', null, null, N'多单位联合共建', N'是', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-02 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'16', N'15', N'15', N'15', N'15', N'重点实验室', N'省级', null, null, N'独建', N'是', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-03 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'17', N'16', N'16', N'16', N'16', N'产业技术研究院', N'国家级', null, null, N'多单位联合共建', N'是', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-03 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'18', N'17', N'17', N'17', N'17', N'工程技术研究中心', N'省级', null, null, N'独建', N'是', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-03 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'19', N'18', N'18', N'18', N'18', N'重点实验室', N'国家级', null, null, N'多单位联合共建', N'否', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-03 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'20', N'19', N'19', N'19', N'19', N'产业技术研究院', N'省级', null, null, N'多单位联合共建', N'否', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-03 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'21', N'20', N'20', N'20', N'20', N'工程技术研究中心', N'国家级', null, null, N'多单位联合共建', N'否', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-03 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'22', N'21', N'21', N'21', N'21', N'重点实验室', N'省级', null, null, N'多单位联合共建', N'是', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-03 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'23', N'22', N'22', N'22', N'22', N'产业技术研究院', N'国家级', null, null, N'多单位联合共建', N'是', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-04 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'24', N'23', N'23', N'23', N'23', N'工程技术研究中心', N'省级', null, null, N'多单位联合共建', N'否', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-04 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'25', N'24', N'24', N'24', N'24', N'重点实验室', N'国家级', null, null, N'多单位联合共建', N'是', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-04 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'26', N'25', N'25', N'25', N'25', N'产业技术研究院', N'省级', null, null, N'独建', N'否', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-04 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'27', N'26', N'26', N'26', N'26', N'工程技术研究中心', N'国家级', null, null, N'独建', N'否', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-04 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'28', N'27', N'27', N'27', N'27', N'重点实验室', N'省级', null, null, N'独建', N'否', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-04 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'29', N'28', N'28', N'28', N'28', N'产业技术研究院', N'国家级', null, null, N'独建', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-05 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'30', N'29', N'29', N'29', N'29', N'工程技术研究中心', N'省级', null, null, N'独建', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-05 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'31', N'30', N'30', N'30', N'30', N'重点实验室', N'国家级', null, null, N'独建', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-05 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'32', N'31', N'31', N'31', N'31', N'产业技术研究院', N'省级', null, null, N'独建', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-05 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'33', N'32', N'32', N'32', N'32', N'工程技术研究中心', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-05 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'34', N'33', N'33', N'33', N'33', N'重点实验室', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-05 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'35', N'34', N'34', N'34', N'34', N'产业技术研究院', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-05 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'36', N'35', N'35', N'35', N'35', N'工程技术研究中心', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-05 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'37', N'36', N'36', N'36', N'36', N'重点实验室', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-06 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'38', N'37', N'37', N'37', N'37', N'产业技术研究院', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-06 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'39', N'38', N'38', N'38', N'38', N'工程技术研究中心', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-06 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'40', N'39', N'39', N'39', N'39', N'重点实验室', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-06 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'41', N'40', N'40', N'40', N'40', N'产业技术研究院', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-06 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'42', N'41', N'41', N'41', N'41', N'工程技术研究中心', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-06 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'43', N'42', N'42', N'42', N'42', N'重点实验室', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-06 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'44', N'43', N'43', N'43', N'43', N'产业技术研究院', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-07 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'45', N'44', N'44', N'44', N'44', N'工程技术研究中心', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-07 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'46', N'45', N'45', N'45', N'45', N'重点实验室', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-07 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'47', N'46', N'46', N'46', N'46', N'产业技术研究院', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-07 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'48', N'47', N'47', N'47', N'47', N'工程技术研究中心', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-07 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'49', N'48', N'48', N'48', N'48', N'重点实验室', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-07 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'50', N'49', N'49', N'49', N'49', N'产业技术研究院', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-07 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'51', N'50', N'50', N'50', N'50', N'工程技术研究中心', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-08 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'52', N'51', N'51', N'51', N'51', N'重点实验室', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-08 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'53', N'52', N'52', N'52', N'52', N'产业技术研究院', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-08 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'54', N'53', N'53', N'53', N'53', N'工程技术研究中心', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-08 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'55', N'54', N'54', N'54', N'54', N'重点实验室', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-08 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'56', N'55', N'55', N'55', N'55', N'产业技术研究院', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-09 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'57', N'56', N'56', N'56', N'56', N'工程技术研究中心', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-09 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'58', N'57', N'57', N'57', N'57', N'重点实验室', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-09 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'59', N'58', N'58', N'58', N'58', N'产业技术研究院', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-09 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'60', N'59', N'59', N'59', N'59', N'工程技术研究中心', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-09 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'61', N'60', N'60', N'60', N'60', N'重点实验室', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-09 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'62', N'61', N'61', N'61', N'61', N'产业技术研究院', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-10 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'63', N'62', N'62', N'62', N'62', N'工程技术研究中心', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-10 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'64', N'63', N'63', N'63', N'63', N'重点实验室', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-10 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'65', N'64', N'64', N'64', N'64', N'产业技术研究院', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-10 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'66', N'65', N'65', N'65', N'65', N'工程技术研究中心', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-10 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'67', N'66', N'66', N'66', N'66', N'重点实验室', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-10 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'68', N'67', N'67', N'67', N'67', N'产业技术研究院', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-10 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'69', N'68', N'68', N'68', N'68', N'工程技术研究中心', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-10 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'70', N'69', N'69', N'69', N'69', N'重点实验室', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-10 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'71', N'70', N'70', N'70', N'70', N'产业技术研究院', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-10 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'72', N'71', N'71', N'71', N'71', N'工程技术研究中心', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N'2018-06-10 00:00:00.000', null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'73', N'72', N'72', N'72', N'72', N'重点实验室', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'74', N'73', N'73', N'73', N'73', N'产业技术研究院', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'75', N'74', N'74', N'74', N'74', N'工程技术研究中心', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'76', N'75', N'75', N'75', N'75', N'重点实验室', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'77', N'76', N'76', N'76', N'76', N'产业技术研究院', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'78', N'77', N'77', N'77', N'77', N'工程技术研究中心', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'79', N'78', N'78', N'78', N'78', N'重点实验室', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'80', N'79', N'79', N'79', N'79', N'产业技术研究院', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'81', N'80', N'80', N'80', N'80', N'工程技术研究中心', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'82', N'81', N'81', N'81', N'81', N'重点实验室', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'83', N'82', N'82', N'82', N'82', N'产业技术研究院', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'84', N'83', N'83', N'83', N'83', N'工程技术研究中心', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'85', N'84', N'84', N'84', N'84', N'重点实验室', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'86', N'85', N'85', N'85', N'85', N'产业技术研究院', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'87', N'86', N'86', N'86', N'86', N'工程技术研究中心', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'88', N'87', N'87', N'87', N'87', N'重点实验室', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'89', N'88', N'88', N'88', N'88', N'产业技术研究院', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'90', N'89', N'89', N'89', N'89', N'工程技术研究中心', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'91', N'90', N'90', N'90', N'90', N'重点实验室', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'92', N'91', N'91', N'91', N'91', N'产业技术研究院', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'93', N'92', N'92', N'92', N'92', N'工程技术研究中心', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'94', N'93', N'93', N'93', N'93', N'重点实验室', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'95', N'94', N'94', N'94', N'94', N'产业技术研究院', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'96', N'95', N'95', N'95', N'95', N'工程技术研究中心', N'省级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
INSERT INTO [dbo].[t_user] ([id], [platformid], [password], [platformname], [platformpizhunnum], [platformtechnology], [platformjibie], [platformadress], [platformxingtai], [gongjiandujian], [jingjinji], [jingjihangye], [mainxueku], [danweiname], [danweidaima], [danweifaren], [danweiphone], [danweileixing], [gongjiandanwei], [yzname], [yzsex], [yzbirth], [yzzhicheng], [yzzhuanye], [yzxueli], [yzxuewei], [yzphonenum], [yzofficialnum], [yzemail], [platwebname], [webadress], [tongxunadress], [youbian], [platformdate], [quanxian]) VALUES (N'97', N'96', N'96', N'96', N'96', N'重点实验室', N'国家级', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
GO
GO
SET IDENTITY_INSERT [dbo].[t_user] OFF
GO
